### ISSUE TITLE
With method delete extra string is added in URL

### ISSUE THREAD

**Issue by QHose** [stefanwalther/qrs#9]
Hi Stefan,

I noticed that if I wanted to delete an app with url

```
function deleteApp (guid) {
    return qrs.delete('/qrs/app/'+guid,)
    .catch(err => {
        console.log(err);
        throw new Meteor.Error(err)
    })
};
```

it shows this in the log, it , I think, incorrectly adds the undefined string in the URL?
/hdr/qrs/app/6951a182-9bdf-4353-a306-1f1f800e46ed/undefined/?xrfkey=ABCDEFG123456789'

if I do this

```
function deleteApp (guid) {
    return qrs.delete('/qrs/app/'+guid, null, null)
    .catch(err => {
        console.log(err);
        throw new Meteor.Error(err)
    })
};
```

it replaces undefined in the example above by null

```
request:
 { domain: null,
   _events: [Object],
   _maxListeners: 10,
   method: 'DELETE',
   headers: [Object],
   proxy: null,
   timeout: 2000,
   callback: [Function],
   readable: true,
   writable: true,
   explicitMethod: true,
   _qs: [Object],
   _auth: [Object],
   _oauth: [Object],
   _multipart: [Object],
   _redirect: [Object],
   _tunnel: [Object],
   setHeader: [Function],
   hasHeader: [Function],
   getHeader: [Function],
   removeHeader: [Function],
   localAddress: undefined,
   pool: {},
   dests: [],
   __isRequestRequest: true,
   _callback: [Function],
   uri: [Object],
   tunnel: false,
   setHost: true,
   originalCookieHeader: undefined,
   _disableCookies: true,
   _jar: undefined,
   port: 80,
   host: '2008ent',
   path: '/hdr/qrs/app/6951a182-9bdf-4353-a306-1f1f800e46ed/null/?xrfkey=ABCDEFG123456789',
   httpModule: [Object],
   agentClass: [Object],
   agent: [Object],
   _started: true,
   href: 'http://2008ent/hdr/qrs/app/6951a182-9bdf-4353-a306-1f1f800e46ed/null/?xrfkey=ABCDEFG123456789',
   req: [Object],
   timeoutTimer: null,
   ntick: true,
   response: [Circular],
   originalHost: '2008ent',
   originalHostHeaderName: 'host',
   responseContent: [Circular],
   _destdata: true,
   _ended: true,
   _callbackCalled: true },
toJSON: [Function: responseToJSON],
caseless: { dict: [Object] },
pipe: [Function],
addListener: [Function: addListener],
on: [Function: addListener],
pause: [Function],
resume: [Function],
read: [Function],
body: 'No matching endpoint found' } }
```

if I try {} in stead of null, I get our old issue back (push)

```

Exception while invoking method 'deleteApp' TypeError: Object [object Object] has no method 'push'
    at qrs.getUrl (C:\Users\Qlik\Meteor projects\qrsmeteor\node_modules\qrs\lib\qrs.js:253:10)
    at qrs.request (C:\Users\Qlik\Meteor projects\qrsmeteor\node_modules\qrs\lib\qrs.js:90:19)
    at qrs.delete (C:\Users\Qlik\Meteor projects\qrsmeteor\node_modules\qrs\lib\qrs.js:225:15)
    at _deleteApp (server/main.js:97:9)
    at [object Object].deleteApp (server/main.js:157:3)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
```

**Comment by stefanwalther** [comment]
Thx for reporting, I'll investigate.
